### ISSUE TITLE
Add support for --no-deps flag

### ISSUE THREAD

**Issue by jdheyburn** [tobilg/python-lambda-layer-builder#1]
Nice work on this - looks very helpful!

One small suggestion, in some cases when creating a lambda layer, we may not want pull in dependencies when we `pip install` because we could be pulling them from another layer. 

Example case in this blog post re `numpy`: https://medium.com/@qtangs/creating-new-aws-lambda-layer-for-python-pandas-library-348b126e9f3e

So I think an additional flag that is passed down to `_make.sh` to then invoke `--no-deps` on the `pip install` would be beneficial.

**Comment by tobilg** [comment]
Hi @jdheyburn, thanks for the feedback! I'll look into that really soon.

**Comment by tobilg** [comment]
This was implemented in ac39cd9.
