### ISSUE TITLE
Python 3.8 Support

### ISSUE THREAD

**Issue by ShaunEdiger** [tobilg/python-lambda-layer-builder#3]
Love the project!  I was glueing things together with my own bash scripts, but this makes it a bit more standardized.

Are there plans for supporting 3.8?  I wanted to file an issue before taking action so we can avoid any duplicated efforts.  I haven't looked into how much effort is involved

**Comment by tobilg** [comment]
Thanks a lot, glad that the project is useful for you. As the respective Docker image exists with he `3.8` tag (https://hub.docker.com/layers/lambci/lambda/build-python3.8/images/sha256-8407325789c8dcaac09d1f5fc7a691716d52e6ec365d2f4d8701f0e06e6b440b?context=explore) I think you could try to specify the `-p 3.8` flag and see how this goes.

**Comment by vasudev-gm** [comment]
@tobilg Thanks for the package. I will test python 3.8 and will report how it went! I was pulling my hairs out to get AWS Lambda Layers to work properly!

**Comment by vasudev-gm** [comment]
Hey tobilg, The package worked after providing -s parameter. 
After stripping .so files lambda python function threw an error: "ELF load command address/offset not properly aligned". 
So, I believe the stock settings should be without -s. 
Thank you.

**Comment by tobilg** [comment]
Thanks for the feedback @vasudev-gm I kind of hesitate to make it a default setting, if people need the .so files they can always use the -s flag. 

@ShaunEdiger were you successful with Python 3.8 as well?

**Comment by vasudev-gm** [comment]
> Thanks for the feedback @vasudev-gm I kind of hesitate to make it a default setting, if people need the .so files they can always use the -s flag.
> 
> @ShaunEdiger were you successful with Python 3.8 as well?

You're welcome. 
I'm sorry for that earlier comment, it seems I ate few words whilst typing! It should have been; **Without** -s

**Comment by ShaunEdiger** [comment]
Sorry for the delay, guys.  It built the layer without any apparent issue.  The README documentation threw me off because the versions maxed out at 3.7.

My command:

```bash
./build.sh \
  -p 3.8 \
  -n insert-project-name-here \
  -s
```

**Comment by tobilg** [comment]
Thanks for the feedback, I’ll update the README. Can I close the issue?

**Comment by ShaunEdiger** [comment]
No objections from me!

**Comment by tobilg** [comment]
I updated the README in b6541bb4a7663be885d4a5144ca3f379bf2c25c4. Thanks again!
